### ISSUE TITLE
Switching to noarch Python

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/holoviews-feedstock#16]
Seems like it might be reasonable to convert this package into a [`noarch: python`]( https://conda-forge.org/docs/meta.html#building-noarch-packages ) one. Curious if that is acceptable with the maintainers/developers. If so, this would greatly simplify the update process going forward.

**Comment by jlstevens** [comment]
I absolutely agree! 

Historically, the problem is that noarch conda package support has been flakey in some areas. That might be fixed though but because of bad past experiences I am reluctant to experiment with it. That said I would love it if noarch worked flawlessly the way I think it should given that holoviews is a pure python package!

**Comment by jakirkham** [comment]
Yeah `noarch_python: True` (the old noarch packages) seems to have been pretty rough for people. The `noarch: python` approach has been pretty good, but it is definitely young. Only things worth noting are a recipe cannot have selectors, no pre/post link or activate/deactivate scripts, and no content can be installed outside site-packages (except entrypoints) currently. The last point has changed in newer `conda-build`s, but we are not there yet. Also I think Python 2/3 compatibility is a requirement, but am much less sure of how true that is in actuality.

**Comment by jlstevens** [comment]
I am attempting to switch to ``noarch`` on the ``dev`` branch in #29. I notice that Travis still builds for the different Python versions?

![image](https://user-images.githubusercontent.com/890576/38208975-ab55861c-36aa-11e8-9f3b-899b5a142f2a.png)

@jakirkham Perhaps you know if I missed something?

**Comment by jakirkham** [comment]
Yep, needs a re-render. Should now be done.

ref: https://github.com/conda-forge/holoviews-feedstock/pull/29#issuecomment-378006553

**Comment by jakirkham** [comment]
Addressed in PR ( https://github.com/conda-forge/holoviews-feedstock/pull/31 ).
